name: Docker Publish

on:
  release:
    types: [published]  # se d√©clenche sur chaque release GitHub

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # ton username Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # ton mot de passe Docker Hub

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .             # dossier du projet
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tech-web:latest  # image finale
